before_script:
  - psql -c 'create database sqlalchemy_i18n_test;' -U postgres

language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -e ".[test]"
script:
  - isort --verbose --recursive --diff sqlalchemy_i18n tests && isort --verbose --recursive --check-only sqlalchemy_i18n tests
  - flake8 sqlalchemy_i18n tests
  - python setup.py test
